const H='https://images.unsplash.com/';
const FALLBACK='https://images.unsplash.com/photo-1549490349-8643362247b5?auto=format&fit=crop&q=86&w=1200';
const data={works:[['김선우','Moment of Bloom','photo-1547891654-e66ed7ebb968','₩2,800,000'],['Shin Dain','Blue Ketchup, 2025','photo-1541961017774-22349e4a1262','Price on request'],['최유진','Light within','photo-1579783902614-a3fb3927b6a5','₩3,500,000'],['박서현','After the Rain','photo-1561440238-08eade76a77e','₩1,800,000']],exh:[['Flowers','HERAS ART GALLERY','photo-1770747717041-069127dad7d8'],['감각의 지도','리움미술관','photo-1561214115-f2f134cc4912'],['더 가까운 세계','국립현대미술관','photo-1577083165633-14ebcdb0f658']],gals:[['HERAS ART GALLERY','판교','photo-1774021802549-d34b0a3c5750'],['PKM Gallery','서울','photo-1561214115-f2f134cc4912'],['국제갤러리','서울','photo-1577083165633-14ebcdb0f658'],['조현화랑','부산','photo-1572953109213-3be62398eb95']],guides:[['The Quiet Power of Everyday','ARTIST · Shin Dain','photo-1494438639946-1ebd1d20bf85'],['좋은 전시를 고르는 법','CULTURE','photo-1545987796-200677ee1011'],['첫 작품을 살 때 꼭 보는 7가지','COLLECTING','photo-1600210492486-724fe5c67fb0']]};
const img=(id,w=900)=>`${H}${id}?auto=format&fit=crop&q=86&w=${w}`;
const safeImg=(src,extra='')=>`<img src="${src}" onerror="if(!this.dataset.fallbacked){this.dataset.fallbacked='1';this.src='${FALLBACK}';}" ${extra}>`;
function workCard(w){return `<article class="work" onclick="go('artwork')">${safeImg(img(w[2]))}<h4>${w[0]}</h4><div class="name">${w[1]}</div><div class="price">${w[3]}</div></article>`}
function tile(t,type){return `<article class="tile wide" onclick="go('${type}')">${safeImg(img(t[2],1200))}<div class="meta">${t[1]}</div><h3 class="serif">${t[0]}</h3></article>`}
function home(){return `<section class="hero"><div class="heroCopy"><div class="kicker">ART LIVES A RICHER LIFE</div><h1 class="serif">A More<br>Contemporary<br>World</h1><p>예술이 만드는 더 깊고, 더 다채로운 일상. KCAC가 함께합니다.</p><a class="btn" href="#discover">지금, 예술을 만나는 방법 →</a></div></section><div class="wrap home"><section class="section cols"><div><div class="titleRow"><div><h2 class="serif">For You</h2><span class="sub">이수아님을 위한 추천 작품</span></div><a class="more" href="#discover">더보기 →</a></div><div class="grid4">${data.works.map(workCard).join('')}</div></div><div class="interview"><div class="txt"><div class="kicker">ARTIST INTERVIEW</div><h3 class="serif">The Quiet Power of Everyday</h3><p>“일상의 감정이 모여, 지금의 작업이 되었습니다.” Shin Dain의 작업 세계를 만나보세요.</p><a class="more" href="#guide-detail">작가 인터뷰 보기 →</a></div>${safeImg(img('photo-1494438639946-1ebd1d20bf85',1000))}</div></section><section class="section cols"><div><div class="titleRow"><div><h2 class="serif">Exhibition Picks</h2><span class="sub">지금, 주목해야 할 전시</span></div><a class="more" href="#exhibitions">전체 보기 →</a></div><div class="grid3">${data.exh.map(x=>tile(x,'exhibition-detail')).join('')}</div></div><div class="first"><div class="kicker">FIRST ART · START YOUR COLLECTION</div><h3 class="serif">처음 만나는, 나의 예술</h3><p class="sub">예산에 맞는 작품을 추천받고 나만의 첫 컬렉션을 시작해보세요.</p><div class="chips"><span class="chip">30만원 이하</span><span class="chip">50만원 이하</span><span class="chip">100만원 이하</span><span class="chip">300만원 이하</span></div><p><a class="more" href="#firstart">나에게 맞는 작품 찾기 →</a></p></div></section><section class="section"><div class="titleRow"><div><h2 class="serif">Curated Collections</h2><span class="sub">지금, 주목할 만한 큐레이션</span></div><a class="more" href="#curations">전체 보기 →</a></div><div class="collections">${[['A New Beginning','photo-1618221195710-dd6b41faaea6'],['Colors of Tomorrow','photo-1579783902614-a3fb3927b6a5'],['Living with Art','photo-1600210492486-724fe5c67fb0'],['Korean Contemporary','photo-1549490349-8643362247b5']].map(x=>`<div class="collection">${safeImg(img(x[1]))}<div><h3 class="serif">${x[0]}</h3><span class="sub" style="color:#fff">KCAC Curated</span></div></div>`).join('')}</div></section><section class="section split"><div><div class="titleRow"><div><h2 class="serif">Galleries to Discover</h2></div><a href="#galleries" class="more">전체 보기 →</a></div><div class="grid4">${data.gals.map(x=>tile(x,'gallery-detail')).join('')}</div></div><div><div class="titleRow"><div><h2 class="serif">Art Guide</h2></div><a href="#guide" class="more">전체 보기 →</a></div><div class="grid3">${data.guides.map(x=>tile(x,'guide-detail')).join('')}</div></div></section><section class="my"><div class="mybox"><h2 class="serif">My KCAC</h2><p class="sub">좋아요한 작품 12 · 최근 본 작품 28 · 관심 전시 5 · 팔로우한 갤러리 3</p></div><div class="journey"><h2 class="serif">작품과 가까워지는<br>나만의 아트 여정</h2><p>관심 있는 작품, 작가, 갤러리를 한 곳에서.</p></div></section></div>`}
function listPage(title,desc,items,type){return `<div class="wrap"><div class="subtop"><div class="kicker">${title.toUpperCase()}</div><h1 class="serif">${title}</h1><p>${desc}</p></div><div class="toolbar"><div class="filters"><span class="fchip">전체</span><span class="fchip">추천</span><span class="fchip">최신</span><span class="fchip">관심</span></div><span class="sub">추천순⌄</span></div><div class="${type==='artwork'?'grid4':'grid3'}">${items.map(x=>type==='artwork'?workCard(x):tile(x,type+'-detail')).join('')}</div></div>`}
function artwork(){let w=data.works[1];return `<div class="wrap detail"><a class="sub" href="#discover">DISCOVER / ARTWORK</a><div class="detailGrid"><div class="detailMedia">${safeImg(img(w[2],1400))}</div><div class="detailCopy"><div class="kicker">ARTWORK</div><h1 class="serif">${w[1]}</h1><b>${w[0]}</b><p class="meta">Acrylic on canvas · 60.6 × 45.5cm · 2025</p><div class="bigprice">${w[3]}</div><button class="btn">문의하기</button><div class="info"><h4>30초 작품 설명</h4><p>강한 색이 먼저 눈에 들어오지만 화면의 균형은 의외로 조용합니다. 색과 색 사이의 거리가 감정을 조율하며 오래 머물 수 있는 리듬을 만듭니다.</p></div><div class="info"><h4>About the Artist</h4><p>Shin Dain은 내면과 소통하며 채워가는 작업에서 비움의 과정으로 확장해갑니다.</p></div></div></div></div>`}
function exhibitionDetail(){return `<div class="wrap galleryHero">${safeImg(img('photo-1770747717041-069127dad7d8',1600))}<div><div class="kicker">EXHIBITION</div><h1 class="serif">Flowers</h1><p class="meta">HERAS ART GALLERY · 판교 · 2026</p><p>동시대 작가들이 각자의 시선으로 꽃과 감정, 시간의 관계를 해석하는 전시입니다.</p><button class="btn">관심 전시 저장</button></div></div>`}
function galleryDetail(){return `<div class="wrap galleryHero">${safeImg(img('photo-1561214115-f2f134cc4912',1600))}<div><div class="kicker">GALLERY</div><h1 class="serif">HERAS ART GALLERY</h1><p>판교를 기반으로 동시대 작가의 전시와 작품을 소개하는 갤러리. 작가의 작업 세계와 컬렉터의 새로운 발견을 연결합니다.</p><button class="btn">갤러리 팔로우</button></div></div><div class="wrap section"><div class="titleRow"><h2 class="serif">Current Exhibition</h2></div><div class="grid3">${data.exh.slice(0,1).map(x=>tile(x,'exhibition-detail')).join('')}${data.works.slice(0,2).map(x=>workCard(x)).join('')}</div></div>`}
function firstart(){return `<div class="wrap"><div class="subtop"><div class="kicker">FIRST ART</div><h1 class="serif">Find your first art</h1><p>예산 → 공간/용도 → 무드를 선택하면 첫 소장에 맞는 작품을 추천합니다.</p></div><div class="toolbar"><div class="filters"><span class="fchip">30만원 이하</span><span class="fchip">거실</span><span class="fchip">Warm</span></div></div><div class="grid4">${data.works.map(workCard).join('')}</div></div>`}

function curations(){
  const cs=[
    ['처음 만나는 한국 현대미술','첫 컬렉션을 시작하는 사람을 위한 회화와 오브제 셀렉션.','FIRST COLLECTION','12 works','photo-1577083552431-6e5fd01988a5'],
    ['Quiet Objects','조용한 공간에 오래 머무는 작품들. 절제된 색과 물성의 큐레이션.','MOOD · QUIET','9 works','photo-1549490349-8643362247b5'],
    ['Under 3 Million','300만원 이하에서 발견하는 지금 주목할 만한 작품.','PRICE CURATION','16 works','photo-1579783902614-a3fb3927b6a5'],
    ['Living with Art','거실과 일상의 중심에 자연스럽게 놓이는 작품을 골랐습니다.','SPACE · LIVING','11 works','photo-1541961017774-22349e4a1262'],
    ['New Voices','KCAC가 새롭게 발견한 젊은 작가들의 작업.','EMERGING ARTISTS','14 works','photo-1547891654-e66ed7ebb968'],
    ['A Touch of Blue','푸른색이 만드는 온도와 깊이를 따라가는 작품 셀렉션.','COLOR · BLUE','10 works','photo-1561440238-08eade76a77e'],
    ['Small Works, Big Presence','작은 크기지만 공간의 분위기를 선명하게 바꾸는 작품.','SMALL FORMAT','13 works','photo-1577083165633-14ebcdb0f658'],
    ['Weekend Collector','주말에 천천히 보고, 부담 없이 시작하는 첫 구매 제안.','KCAC EDIT','8 works','photo-1561214115-f2f134cc4912']
  ];
  const card=x=>`<article class="curation-card" onclick="go('discover')"><div class="curation-img">${safeImg(img(x[4],900))}</div><div class="curation-meta"><span>${x[2]}</span><span>${x[3]}</span></div><h3 class="serif">${x[0]}</h3><p>${x[1]}</p></article>`;
  const f=cs[0];
  return `<style>
  .curations-page{padding:48px 0 92px}.curations-head{display:flex;align-items:end;justify-content:space-between;gap:28px;padding-bottom:26px;border-bottom:1px solid #111}.curations-head h1{font-size:52px;line-height:.96;letter-spacing:-.05em;margin:8px 0 0}.curations-intro{max-width:420px;font-size:11px;line-height:1.8;color:#777;margin:0 0 3px}.curations-feature{display:grid;grid-template-columns:1.45fr .55fr;gap:22px;padding:34px 0 42px;border-bottom:1px solid #e9e5df;cursor:pointer}.curations-feature-image{min-height:430px;overflow:hidden;background:#f2f0ec}.curations-feature-image img{width:100%;height:100%;min-height:430px;object-fit:cover}.curations-feature-copy{display:flex;flex-direction:column;justify-content:flex-end;padding:10px 0 4px}.curations-feature-copy .meta{display:flex;gap:12px;font-size:9px;letter-spacing:.11em;color:#8b857d;text-transform:uppercase;margin-bottom:14px}.curations-feature-copy h2{font-size:40px;line-height:.98;letter-spacing:-.045em;margin:0 0 14px}.curations-feature-copy p{font-size:12px;line-height:1.75;color:#6f6a63;margin:0 0 22px}.curations-section-head{display:flex;align-items:end;justify-content:space-between;padding:34px 0 18px}.curations-section-head h2{font-size:31px;margin:0}.curations-section-head span{font-size:10px;color:#999}.curations-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:34px 18px}.curation-card{cursor:pointer;min-width:0}.curation-img{aspect-ratio:1.18/1;overflow:hidden;background:#f2f0ec}.curation-img img{width:100%;height:100%;object-fit:cover}.curation-meta{display:flex;justify-content:space-between;gap:10px;margin:11px 0 7px;font-size:8px;letter-spacing:.12em;color:#938c83;text-transform:uppercase}.curation-card h3{font-size:25px;line-height:1.04;letter-spacing:-.04em;margin:0 0 8px}.curation-card p{font-size:10px;line-height:1.65;color:#777;margin:0;max-width:92%}@media(max-width:900px){.curations-head{align-items:start;flex-direction:column}.curations-feature{grid-template-columns:1fr}.curations-feature-image,.curations-feature-image img{min-height:360px}.curations-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:600px){.curations-page{padding-top:32px}.curations-head h1{font-size:42px}.curations-feature-image,.curations-feature-image img{min-height:280px}.curations-feature-copy h2{font-size:34px}.curations-grid{grid-template-columns:1fr}}
  </style><div class="wrap curations-page"><div class="curations-head"><div><div class="kicker">KCAC CURATIONS</div><h1 class="serif">Curations</h1></div><p class="curations-intro">취향, 공간, 예산, 그리고 지금의 감각을 기준으로 KCAC가 작품을 새롭게 묶어 소개합니다.</p></div><section class="curations-feature" onclick="go('discover')"><div class="curations-feature-image">${safeImg(img(f[4],1500))}</div><div class="curations-feature-copy"><div class="meta"><span>FEATURED CURATION</span><span>${f[3]}</span></div><h2 class="serif">${f[0]}</h2><p>${f[1]}</p><span>→</span></div></section><div class="curations-section-head"><h2 class="serif">Explore Curations</h2><span>${cs.length-1} selections</span></div><section class="curations-grid">${cs.slice(1).map(card).join('')}</section></div>`;
}

function guideDetail(){return `<div class="wrap subtop"><div class="kicker">ARTIST INTERVIEW · SHIN DAIN</div><h1 class="serif">The Quiet Power of Everyday</h1><p>내면과 소통하며 채워가는 작업에서 비움의 과정으로.</p></div><article class="article"><p class="quote">“좋은 작품은 답을 주기보다, 감정이 머물 수 있는 공간을 만든다.”</p><h2>일상의 감정을 작업으로 옮기는 법</h2><p>신다인의 화면에는 익숙한 형태와 색이 등장하지만 하나의 장면을 설명하기보다 감정의 흐름을 남기는 데 집중합니다.</p><h2>Blue Ketchup, 2025</h2><p>강한 색감이 먼저 눈에 들어오지만 가까이 보면 화면의 균형은 의외로 조용합니다.</p></article>`}
function render(){let r=location.hash.slice(1)||'home',html='';if(r==='home')html=home();else if(r==='discover')html=listPage('Discover','작품, 작가, 갤러리를 취향과 가격대, 분위기로 탐색하세요.',data.works,'artwork');else if(r==='artwork')html=artwork();else if(r==='exhibitions')html=listPage('Exhibitions','지금 주목해야 할 전시를 저장하고 방문 예정으로 관리하세요.',data.exh,'exhibition');else if(r==='exhibition-detail')html=exhibitionDetail();else if(r==='firstart')html=firstart();else if(r==='galleries')html=listPage('Galleries','새로운 작가를 발굴하고 전시를 만드는 갤러리를 만나보세요.',data.gals,'gallery');else if(r==='gallery-detail')html=galleryDetail();else if(r==='guide')html=listPage('Art Guide','작품을 보는 법부터 첫 구매와 컬렉션까지.',data.guides,'guide');else if(r==='guide-detail')html=guideDetail();else if(r==='curations')html=curations();else html=home();document.getElementById('app').innerHTML=html;window.scrollTo(0,0)}
window.go=x=>location.hash=x;window.addEventListener('hashchange',render);render();